const hueWards = [
  { id: 19753, ten: "Phu Xuan", loai: "phuong" },
  { id: 19774, ten: "Kim Long", loai: "phuong" },
  { id: 19777, ten: "Vy Da", loai: "phuong" },
  { id: 19789, ten: "Thuan Hoa", loai: "phuong" },
  { id: 19804, ten: "Huong An", loai: "phuong" },
  { id: 19813, ten: "Thuy Xuan", loai: "phuong" },
  { id: 19815, ten: "An Cuu", loai: "phuong" },
  { id: 19819, ten: "Phong Dien", loai: "phuong" },
  { id: 19828, ten: "Phong Phu", loai: "phuong" },
  { id: 19831, ten: "Phong Dinh", loai: "phuong" },
  { id: 19858, ten: "Phong Thai", loai: "phuong" },
  { id: 19873, ten: "Phong Quang", loai: "phuong" },
  { id: 19900, ten: "Thuan An", loai: "phuong" },
  { id: 19909, ten: "Duong No", loai: "phuong" },
  { id: 19930, ten: "My Thuong", loai: "phuong" },
  { id: 19960, ten: "Phu Bai", loai: "phuong" },
  { id: 19969, ten: "Thanh Thuy", loai: "phuong" },
  { id: 19975, ten: "Huong Thuy", loai: "phuong" },
  { id: 19996, ten: "Huong Tra", loai: "phuong" },
  { id: 20014, ten: "Hoa Chau", loai: "phuong" },
  { id: 20017, ten: "Kim Tra", loai: "phuong" },

  { id: 19867, ten: "Quang Dien", loai: "xa" },
  { id: 19885, ten: "Dan Dien", loai: "xa" },
  { id: 19918, ten: "Phu Ho", loai: "xa" },
  { id: 19942, ten: "Phu Vang", loai: "xa" },
  { id: 19945, ten: "Phu Vinh", loai: "xa" },
  { id: 20035, ten: "Binh Dien", loai: "xa" },
  { id: 20044, ten: "A Luoi 2", loai: "xa" },
  { id: 20050, ten: "A Luoi 5", loai: "xa" },
  { id: 20056, ten: "A Luoi 1", loai: "xa" },
  { id: 20071, ten: "A Luoi 3", loai: "xa" },
  { id: 20101, ten: "A Luoi 4", loai: "xa" },
  { id: 20107, ten: "Phu Loc", loai: "xa" },
  { id: 20122, ten: "Vinh Loc", loai: "xa" },
  { id: 20131, ten: "Hung Loc", loai: "xa" },
  { id: 20137, ten: "Chan May - Lang Co", loai: "xa" },
  { id: 20140, ten: "Loc An", loai: "xa" },
  { id: 20161, ten: "Khe Tre", loai: "xa" },
  { id: 20179, ten: "Nam Dong", loai: "xa" },
  { id: 20182, ten: "Long Quang", loai: "xa" },
];
const cameraLists = [
  { id: 1, name: "camera 1", status: 1 },
  { id: 2, name: "camera 2", status: 0 },
  { id: 3, name: "camera 3", status: 0 },
  { id: 4, name: "camera 4", status: 1 },
  { id: 5, name: "camera 5", status: 0 },
  { id: 6, name: "camera 6", status: 0 },
  { id: 7, name: "camera 7", status: 1 },
  { id: 8, name: "camera 8", status: 0 },
  { id: 9, name: "camera 9", status: 1 },
  { id: 10, name: "camera 10", status: 0 },
];
module.exports = { cameraLists, hueWards };
